name: Cancel
on:
  workflow_run:
    workflows:
      - "main"
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: hanabi1224/cancel-workflow-action@120898519f2940069cc6a070c4f9c3d6cc2e7ff8
        with:
          workflow_id: ${{ github.event.workflow.id }}
          all_but_latest: true
          ignore_branches_on_push: |
            main
            master
