name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  task:
    runs-on: ubuntu-latest
    name: main
    steps:
      - uses: actions/setup-node@v3
      - run: echo 'Sleeping...'; sleep 60; echo 'Done.';
